language: node_js
node_js:
  - '10'

jobs:
  include:
    - stage: release
      node_js: 10
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release