language: node_js
node_js:
  - '12'
  - '10'
  - '8'

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release